import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const dataPath = join(import.meta.dirname, '../src/data.json');
const typesPath = join(import.meta.dirname, '../src/generated-types.gen.ts');
const pkgPath = join(import.meta.dirname, '../package.json');

type ProviderData = { name: string; models: Record<string, { name: string }> };
type Data = Record<string, ProviderData>;
type Pkg = { exports: Record<string, unknown> };

const data: Data = JSON.parse(await readFile(dataPath, 'utf-8'));
const pkg: Pkg = JSON.parse(await readFile(pkgPath, 'utf-8'));

const providerIds = Object.keys(data);
const modelIdsByProvider: Record<string, string[]> = {};

for (const providerId of providerIds) {
  modelIdsByProvider[providerId] = Object.keys(data[providerId].models);
}

const quote = (value: string) => JSON.stringify(value);

const typeLines = [
  '// Auto-generated by scripts/generate-types.ts — do not edit manually',
  '/* eslint-disable */',
  '',
  'export type ProviderId =',
  ...providerIds.map((id, index) => `  ${index === 0 ? '' : '| '}${quote(id)}`),
  ';',
  '',
  'export type ModelIdsByProvider = {',
  ...providerIds.map((pid) => `  ${quote(pid)}: ${modelIdsByProvider[pid].map(quote).join(' | ')};`),
  '};',
];

await writeFile(typesPath, typeLines.join('\n') + '\n', 'utf-8');

const adapterExports = Object.fromEntries(
  providerIds.map((pid) => [
    `./${pid}`,
    {
      import: { types: `./dist/adapters/${pid}.d.mts`, default: `./dist/adapters/${pid}.mjs` },
      require: { types: `./dist/adapters/${pid}.d.ts`, default: `./dist/adapters/${pid}.js` },
    },
  ]),
);

pkg.exports = { '.': pkg.exports['.'], './async': pkg.exports['./async'], ...adapterExports };

await writeFile(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf-8');

const totalModels = providerIds.reduce((total, pid) => total + modelIdsByProvider[pid].length, 0);
console.log(`Generated types: ${providerIds.length} providers, ${totalModels} models`);
console.log(`Updated package.json exports: ${providerIds.length + 2} entries`);
